mongo:
  host: 'localhost'
  port: 27017
  database: 'caoyuan_ocr'
  username:
  password:

upload_dir : '/data2/application/caoyuan_ocr/upload'
image_dir : '/data2/application/caoyuan_ocr/image'
template_dir : '/data2/application/caoyuan_ocr/template'