mongo:
  host: 'localhost'
  port: 27017
  database: 'caoyuan_ocr'
  username:
  password:

upload_dir : '/tmp/caoyuan_ocr/upload'
image_dir : '/tmp/caoyuan_ocr/image'
train_dir: '/tmp/caoyuan_ocr/train'
evaluate_dir: '/tmp/caoyuan_ocr/evaluate'